# This docker-compose is only to get started with Conduktor.
# It is starting Conduktor, a Redpanda cluster (Kafka), and a fake app to generate traffic.

# Go to http://localhost:8080 when started

####################################################################################################
# DO NOT USE IT IN PRODUCTION
#
# For production, please check: https://docs.conduktor.io/platform/category/deployment-options/
#   to deploy on Kubernetes via Helm, or AWS using Cloudformation.
####################################################################################################

version: '3.8'

services:
  redpanda:
    image: vectorized/redpanda
    container_name: redpanda
    ports:
      - 9092:9092
    deploy:
      resources:
        limits:
          memory: 2g
    command: ["start", "--overprovisioned", "--smp", "1", "--memory", "2G", "--reserve-memory", "0M", "--node-id", "0"]