// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: scheduled.proto

package proto_scheduled

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetScheduledsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetScheduledsReq) Reset() {
	*x = GetScheduledsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheduled_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScheduledsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduledsReq) ProtoMessage() {}

func (x *GetScheduledsReq) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduledsReq.ProtoReflect.Descriptor instead.
func (*GetScheduledsReq) Descriptor() ([]byte, []int) {
	return file_scheduled_proto_rawDescGZIP(), []int{0}
}

type GetScheduledsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scheduleds []*Scheduled `protobuf:"bytes,1,rep,name=Scheduleds,proto3" json:"Scheduleds,omitempty"`
}

func (x *GetScheduledsRes) Reset() {
	*x = GetScheduledsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheduled_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScheduledsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduledsRes) ProtoMessage() {}

func (x *GetScheduledsRes) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduledsRes.ProtoReflect.Descriptor instead.
func (*GetScheduledsRes) Descriptor() ([]byte, []int) {
	return file_scheduled_proto_rawDescGZIP(), []int{1}
}

func (x *GetScheduledsRes) GetScheduleds() []*Scheduled {
	if x != nil {
		return x.Scheduleds
	}
	return nil
}

type GetScheduledReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScheduledId int64 `protobuf:"varint,1,opt,name=ScheduledId,proto3" json:"ScheduledId,omitempty"`
}

func (x *GetScheduledReq) Reset() {
	*x = GetScheduledReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheduled_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScheduledReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduledReq) ProtoMessage() {}

func (x *GetScheduledReq) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduledReq.ProtoReflect.Descriptor instead.
func (*GetScheduledReq) Descriptor() ([]byte, []int) {
	return file_scheduled_proto_rawDescGZIP(), []int{2}
}

func (x *GetScheduledReq) GetScheduledId() int64 {
	if x != nil {
		return x.ScheduledId
	}
	return 0
}

type GetScheduledRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scheduled *Scheduled `protobuf:"bytes,1,opt,name=Scheduled,proto3" json:"Scheduled,omitempty"`
}

func (x *GetScheduledRes) Reset() {
	*x = GetScheduledRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheduled_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScheduledRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduledRes) ProtoMessage() {}

func (x *GetScheduledRes) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduledRes.ProtoReflect.Descriptor instead.
func (*GetScheduledRes) Descriptor() ([]byte, []int) {
	return file_scheduled_proto_rawDescGZIP(), []int{3}
}

func (x *GetScheduledRes) GetScheduled() *Scheduled {
	if x != nil {
		return x.Scheduled
	}
	return nil
}

type CreateScheduledReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scheduled *CreateScheduled `protobuf:"bytes,1,opt,name=Scheduled,proto3" json:"Scheduled,omitempty"`
}

func (x *CreateScheduledReq) Reset() {
	*x = CreateScheduledReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheduled_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateScheduledReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduledReq) ProtoMessage() {}

func (x *CreateScheduledReq) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduledReq.ProtoReflect.Descriptor instead.
func (*CreateScheduledReq) Descriptor() ([]byte, []int) {
	return file_scheduled_proto_rawDescGZIP(), []int{4}
}

func (x *CreateScheduledReq) GetScheduled() *CreateScheduled {
	if x != nil {
		return x.Scheduled
	}
	return nil
}

type CreateScheduledRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scheduled *Scheduled `protobuf:"bytes,1,opt,name=Scheduled,proto3" json:"Scheduled,omitempty"`
}

func (x *CreateScheduledRes) Reset() {
	*x = CreateScheduledRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheduled_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateScheduledRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduledRes) ProtoMessage() {}

func (x *CreateScheduledRes) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduledRes.ProtoReflect.Descriptor instead.
func (*CreateScheduledRes) Descriptor() ([]byte, []int) {
	return file_scheduled_proto_rawDescGZIP(), []int{5}
}

func (x *CreateScheduledRes) GetScheduled() *Scheduled {
	if x != nil {
		return x.Scheduled
	}
	return nil
}

type Scheduled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                       int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	EntryFee                 int64  `protobuf:"varint,3,opt,name=EntryFee,proto3" json:"EntryFee,omitempty"`
	StartTime                int64  `protobuf:"varint,4,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	RecurrencePattern        string `protobuf:"bytes,5,opt,name=RecurrencePattern,proto3" json:"RecurrencePattern,omitempty"`
	RecurrenceStartTimestamp int64  `protobuf:"varint,6,opt,name=RecurrenceStartTimestamp,proto3" json:"RecurrenceStartTimestamp,omitempty"`
	RecurrenceEndTimestamp   int64  `protobuf:"varint,7,opt,name=RecurrenceEndTimestamp,proto3" json:"RecurrenceEndTimestamp,omitempty"`
	MustRenew                bool   `protobuf:"varint,8,opt,name=MustRenew,proto3" json:"MustRenew,omitempty"`
}

func (x *Scheduled) Reset() {
	*x = Scheduled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheduled_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Scheduled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scheduled) ProtoMessage() {}

func (x *Scheduled) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scheduled.ProtoReflect.Descriptor instead.
func (*Scheduled) Descriptor() ([]byte, []int) {
	return file_scheduled_proto_rawDescGZIP(), []int{6}
}

func (x *Scheduled) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Scheduled) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Scheduled) GetEntryFee() int64 {
	if x != nil {
		return x.EntryFee
	}
	return 0
}

func (x *Scheduled) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Scheduled) GetRecurrencePattern() string {
	if x != nil {
		return x.RecurrencePattern
	}
	return ""
}

func (x *Scheduled) GetRecurrenceStartTimestamp() int64 {
	if x != nil {
		return x.RecurrenceStartTimestamp
	}
	return 0
}

func (x *Scheduled) GetRecurrenceEndTimestamp() int64 {
	if x != nil {
		return x.RecurrenceEndTimestamp
	}
	return 0
}

func (x *Scheduled) GetMustRenew() bool {
	if x != nil {
		return x.MustRenew
	}
	return false
}

type CreateScheduled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	EntryFee                 int64  `protobuf:"varint,3,opt,name=EntryFee,proto3" json:"EntryFee,omitempty"`
	StartTime                int64  `protobuf:"varint,4,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	RecurrencePattern        string `protobuf:"bytes,5,opt,name=RecurrencePattern,proto3" json:"RecurrencePattern,omitempty"`
	RecurrenceStartTimestamp int64  `protobuf:"varint,6,opt,name=RecurrenceStartTimestamp,proto3" json:"RecurrenceStartTimestamp,omitempty"`
	RecurrenceEndTimestamp   int64  `protobuf:"varint,7,opt,name=RecurrenceEndTimestamp,proto3" json:"RecurrenceEndTimestamp,omitempty"`
	MustRenew                bool   `protobuf:"varint,8,opt,name=MustRenew,proto3" json:"MustRenew,omitempty"`
}

func (x *CreateScheduled) Reset() {
	*x = CreateScheduled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scheduled_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateScheduled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduled) ProtoMessage() {}

func (x *CreateScheduled) ProtoReflect() protoreflect.Message {
	mi := &file_scheduled_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduled.ProtoReflect.Descriptor instead.
func (*CreateScheduled) Descriptor() ([]byte, []int) {
	return file_scheduled_proto_rawDescGZIP(), []int{7}
}

func (x *CreateScheduled) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateScheduled) GetEntryFee() int64 {
	if x != nil {
		return x.EntryFee
	}
	return 0
}

func (x *CreateScheduled) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CreateScheduled) GetRecurrencePattern() string {
	if x != nil {
		return x.RecurrencePattern
	}
	return ""
}

func (x *CreateScheduled) GetRecurrenceStartTimestamp() int64 {
	if x != nil {
		return x.RecurrenceStartTimestamp
	}
	return 0
}

func (x *CreateScheduled) GetRecurrenceEndTimestamp() int64 {
	if x != nil {
		return x.RecurrenceEndTimestamp
	}
	return 0
}

func (x *CreateScheduled) GetMustRenew() bool {
	if x != nil {
		return x.MustRenew
	}
	return false
}

var File_scheduled_proto protoreflect.FileDescriptor

var file_scheduled_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x64, 0x73, 0x52, 0x65, 0x71, 0x22, 0x3e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x64, 0x73, 0x52, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x0a, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x52, 0x0a, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x64, 0x73, 0x22, 0x33, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x73, 0x12, 0x28, 0x0a,
	0x09, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x52, 0x09, 0x53, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x22, 0x44, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x71, 0x12, 0x2e, 0x0a,
	0x09, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x64, 0x52, 0x09, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x22, 0x3e, 0x0a,
	0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x09, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x64, 0x52, 0x09, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x22, 0xa9, 0x02,
	0x0a, 0x09, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x46, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x46, 0x65, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x52, 0x65, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x52, 0x65, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x3a, 0x0a, 0x18, 0x52, 0x65, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x18, 0x52, 0x65, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x36, 0x0a, 0x16, 0x52, 0x65, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x16, 0x52, 0x65, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x45,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x4d,
	0x75, 0x73, 0x74, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x4d, 0x75, 0x73, 0x74, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x22, 0x9f, 0x02, 0x0a, 0x0f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x46, 0x65, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x46, 0x65, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x52,
	0x65, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x52, 0x65, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x3a, 0x0a, 0x18, 0x52, 0x65, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x18, 0x52, 0x65, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x36, 0x0a, 0x16, 0x52, 0x65, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x16, 0x52, 0x65, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a,
	0x09, 0x4d, 0x75, 0x73, 0x74, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x4d, 0x75, 0x73, 0x74, 0x52, 0x65, 0x6e, 0x65, 0x77, 0x32, 0xc0, 0x01, 0x0a, 0x10,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x37, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64,
	0x73, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x64, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x12, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x47, 0x65,
	0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x3d, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x64, 0x12, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x29,
	0x5a, 0x27, 0x6b, 0x72, 0x6f, 0x77, 0x6e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f,
	0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_scheduled_proto_rawDescOnce sync.Once
	file_scheduled_proto_rawDescData = file_scheduled_proto_rawDesc
)

func file_scheduled_proto_rawDescGZIP() []byte {
	file_scheduled_proto_rawDescOnce.Do(func() {
		file_scheduled_proto_rawDescData = protoimpl.X.CompressGZIP(file_scheduled_proto_rawDescData)
	})
	return file_scheduled_proto_rawDescData
}

var file_scheduled_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_scheduled_proto_goTypes = []interface{}{
	(*GetScheduledsReq)(nil),   // 0: GetScheduledsReq
	(*GetScheduledsRes)(nil),   // 1: GetScheduledsRes
	(*GetScheduledReq)(nil),    // 2: GetScheduledReq
	(*GetScheduledRes)(nil),    // 3: GetScheduledRes
	(*CreateScheduledReq)(nil), // 4: CreateScheduledReq
	(*CreateScheduledRes)(nil), // 5: CreateScheduledRes
	(*Scheduled)(nil),          // 6: Scheduled
	(*CreateScheduled)(nil),    // 7: CreateScheduled
}
var file_scheduled_proto_depIdxs = []int32{
	6, // 0: GetScheduledsRes.Scheduleds:type_name -> Scheduled
	6, // 1: GetScheduledRes.Scheduled:type_name -> Scheduled
	7, // 2: CreateScheduledReq.Scheduled:type_name -> CreateScheduled
	6, // 3: CreateScheduledRes.Scheduled:type_name -> Scheduled
	0, // 4: ScheduledService.GetScheduleds:input_type -> GetScheduledsReq
	2, // 5: ScheduledService.GetScheduled:input_type -> GetScheduledReq
	4, // 6: ScheduledService.CreateScheduled:input_type -> CreateScheduledReq
	1, // 7: ScheduledService.GetScheduleds:output_type -> GetScheduledsRes
	3, // 8: ScheduledService.GetScheduled:output_type -> GetScheduledRes
	5, // 9: ScheduledService.CreateScheduled:output_type -> CreateScheduledRes
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_scheduled_proto_init() }
func file_scheduled_proto_init() {
	if File_scheduled_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scheduled_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScheduledsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scheduled_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScheduledsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scheduled_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScheduledReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scheduled_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScheduledRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scheduled_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateScheduledReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scheduled_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateScheduledRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scheduled_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Scheduled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scheduled_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateScheduled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scheduled_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduled_proto_goTypes,
		DependencyIndexes: file_scheduled_proto_depIdxs,
		MessageInfos:      file_scheduled_proto_msgTypes,
	}.Build()
	File_scheduled_proto = out.File
	file_scheduled_proto_rawDesc = nil
	file_scheduled_proto_goTypes = nil
	file_scheduled_proto_depIdxs = nil
}
